inherit_from: .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3

Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/ModuleLength:
  Exclude:
    - spec/**/*_spec.rb

RSpec/FilePath:
  Exclude:
    - 'spec/lib/bunnyrun_spec.rb'
