version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - run:
          name: Run rspec in parallel
          command: bundle audit check --update
